### PR TITLE
Update main.c, IoT Central App device template added

### PR DESCRIPTION
**Pull request by rickeycv**
-Some comments were added in main.c file.
-IoT Central App device template was added.

### CODE REVIEW

**Comment by ghost** [comment]
Perhaps you aren't aware, but **clickmodules** is a submodule that is pulled in from the repository **github.com/Avnet/clickmodules**.  This is done when you originally clone this repository with the '--recurse' flag.  This option tells github to go out and pull the current 'master' branch from '**github.com/Avnet/clickmodules**'.  So when you update the subdirectory '**clickmodules**' in your repository, that doesn't update **github.com/Avnet/clickmodules**, it only puts it in your local repository.  To update the actual **clickmodules** repository, you have to pull it, update, commit and push it back (or do a pull request).

I'll do that for you in a bit, but I don't think the project will build correctly for you at present if you do a fresh pull and build because the **clickmodules** repository hasn't been updated.

**Comment by rickeycv** [comment]
Yes, as you said it didn’t build because ‘clickmodules’ is outdated. How can I fix this? If I enter to github.com/Avnet/clickmodules I can see the AIRQUALITY5 folder but if I enter from github.com/Avnet/clickboard_demos following the submodule I can’t see the AIRQUALITY5 folder.

Rickey Castillo Valenzuela
rickey.castillo@avid-tech.com<mailto:rickey.castillo@avid-tech.com>
Firmware Engineer
[cid:image001.png@01D5576A.8FE7CA20]
Camino al ITESO 8900 1-B
Parque Industrial Tecnológico Pinar de la Calma
Zapopan, Jalisco, México CP45080
O 52 33 3835 5171
http://www.avid-tech.com<http://www.avid-tech.com/>

**Comment by ghost** [comment]
send me the files that were changed in clickmodules and I'll add them.

**Comment by rickeycv** [comment]
The files are attached, currently they are included in commit number 083235a.

Rickey Castillo Valenzuela
rickey.castillo@avid-tech.com<mailto:rickey.castillo@avid-tech.com>
Firmware Engineer
[cid:image001.png@01D5576F.ED66C7A0]
Camino al ITESO 8900 1-B
Parque Industrial Tecnológico Pinar de la Calma
Zapopan, Jalisco, México CP45080
O 52 33 3835 5171
http://www.avid-tech.com<http://www.avid-tech.com/>

**Comment by ghost** [comment]
I see 3 files changed:
#1) SPHERE_MT3620/AirQuality5_demo/AvnetSphereAirQuality5/main.c
#2) SPHERE_MT3620/AirQuality5_demo/IoT Central App Device template/Device_Export_20190820_161541.csv
#3) .gitmodules (which is point off somewhere I can't get to) which is the clickmodules reference

If no files where changes in clickmodules, then I just need to revert it back to like it was before your pull request.  If you changed some files within clickmodules, then you need to send me those files that changed so I can update the clickmodules repository.

**Comment by ghost** [comment]
BTW, have you worked much with submodules?

**Comment by rickeycv** [comment]
Yes, I changed those 3 files today in clickboard_demos<https://github.com/Avnet/clickboard_demos>. Since yesterday I have not changed clickmodules files.

Rickey Castillo Valenzuela
rickey.castillo@avid-tech.com<mailto:rickey.castillo@avid-tech.com>
Firmware Engineer
[cid:image001.png@01D55773.43EE3D80]
Camino al ITESO 8900 1-B
Parque Industrial Tecnológico Pinar de la Calma
Zapopan, Jalisco, México CP45080
O 52 33 3835 5171
http://www.avid-tech.com<http://www.avid-tech.com/>

**Comment by rickeycv** [comment]
No, this is the second time I work with GitHub submodules. Which do I need to push first, submodule or module?

Rickey Castillo Valenzuela
rickey.castillo@avid-tech.com<mailto:rickey.castillo@avid-tech.com>
Firmware Engineer
[cid:image001.png@01D55774.0E11D450]
Camino al ITESO 8900 1-B
Parque Industrial Tecnológico Pinar de la Calma
Zapopan, Jalisco, México CP45080
O 52 33 3835 5171
http://www.avid-tech.com<http://www.avid-tech.com/>

**Comment by ghost** [comment]
In that case, do a new pull and try it. I reverted the clickmodules reference back to what it was yesterday and if you didn't change anything in that submodule you should have no problem.

**Comment by rickeycv** [comment]
I did a fresh pull and it’s working now. Thanks.

Rickey Castillo Valenzuela
rickey.castillo@avid-tech.com<mailto:rickey.castillo@avid-tech.com>
Firmware Engineer
[cid:image001.png@01D55776.7A0541E0]
Camino al ITESO 8900 1-B
Parque Industrial Tecnológico Pinar de la Calma
Zapopan, Jalisco, México CP45080
O 52 33 3835 5171
http://www.avid-tech.com<http://www.avid-tech.com/>

**Comment by ghost** [comment]
I usually finalize the sub module first. That way you can update the references when you submit the projects that use it.

**Pull request merged**
